In [ ]:
#reading Video
import cv2 as cv
capture=cv.VideoCapture('Screen Recording 2025-02-01 190541.mp4')
while True:
    isTrue, Frame=capture.read()
    cv.imshow('video',Frame)
    if cv.waitKey(20) & 0xFF==ord('d'):
        break
capture.release()
capture.destroyAllwindows()

error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [ ]:
import os 
os.getcwd()
os.chdir(r"D:\main"
         )
os.getcwd()
# os.makedirs(r'D:\main\testing')
os.listdir(r'D:\main')
# os.removedirs(r'D:\main\testing')
os.rename(r"D:\main\PetImages",r"D:\main\PetImages_img")


In [19]:
# print(dir(os.path))
os.path.exists(r"D:\main\PetImages_img")

True

In [ ]:
# rescale
img=cv.imread("Screenshot 2025-06-12 085032.png")
cv.imshow(img)
def resimg(img,scale=0.75):
    width=int(img.shape[1]*scale)
    height=int(img.shape[0]*scale)
    dimeansion=(width,heigth)


error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import pandas as 
df=pd.read_csv('Titanic-Dataset.csv')

NameError: name 'pd' is not defined

NameError: name 'x' is not defined

In [7]:
from sklearn.preprocessing import MinMaxScaler
scx=MinMaxScaler()
scy=MinMaxScaler()

In [13]:
x_scaled=scx.fit_transform(df.drop('price',axis='columns'))
y_scaled=scy.fit_transform(df['price'].values.reshape(-1,1))

In [25]:
x_scaled

array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [28]:
def grad_descent(x,y_true,epoch,learning_rate=0.01):
    number_of_features=x.shape[1]
    w=np.ones(shape=(number_of_features))
    b=0
    total=x.shape[0]
    cost_list=[]
    epoch_list=[]
    for i in  range(epoch):
        y_pred=np.dot(w,x.T)+b
        w_grad=-(2/total)*(x.T.dot(y_true-y_pred))
        b_grad=-(2/total)*np.sum(y_true-y_pred) 
        w=w-learning_rate*w_grad
        b=b-learning_rate*b_grad
        cost=np.mean(np.square(y_true-y_pred))
        if i%10==0:
            cost_list.append(cost)
            epoch_list.append(i)
        return w,b,cost,cost_list,epoch_list
w,b,cost,cost_list,epoch_list=grad_descent(x_scaled,y_scaled,10)


ValueError: operands could not be broadcast together with shapes (2,) (2,20) 

In [ ]:
np.ones(shape=(2))

array([1., 1.])

In [20]:
np.zeros(1)

array([0.])

AttributeError: 'list' object has no attribute 'T'